export const data = [
  {
    id: "qwertyunfbj12",
    year: 2017,
    date: "5/4/2017",
    city: "Hyderabad",
    tossWin: "Royal Challengers Bangalore",
    tossDecision: "field",
    team1: "Sunrisers Hyderabad",
    team2: "Royal Challengers Bangalore",
    winner: "Sunrisers Hyderabad",
    winByRun: "35",
    winByWicket: "0",
    playerOfMatch: "Yuvraj Singh",
  },
  {
    id: "qwerbkstyun13",
    year: 2017,
    date: "6/4/2017",
    city: "pune",
    tossWin: "Rising Pune Supergiant",
    tossDecision: "field",
    team1: "Mumbai Indians",
    team2: "Rising Pune Supergiant",
    winner: "Rising Pune Supergiant",
    winByRun: "0",
    winByWicket: "7",
    playerOfMatch: "SPD Smith",
  },
  {
    id: "qwerty787un12",
    year: 2017,
    date: "7/4/2017",
    city: "Rajkot",
    tossWin: "Kolkata Knight Riders",
    tossDecision: "Bat",
    team1: "Gujarat Lions",
    team2: "Kolkata Knight Riders",
    winner: "Kolkata Knight Riders",
    winByRun: "0",
    winByWicket: "10",
    playerOfMatch: "CA Lynn",
  },
  {
    id: "qwertdfdyun12",
    year: 2017,
    date: "5/4/2017",
    city: "Hyderabad",
    tossWin: "Royal Challengers Bangalore",
    tossDecision: "field",
    team1: "Sunrisers Hyderabad",
    team2: "Royal Challengers Bangalore",
    winner: "Sunrisers Hyderabad",
    winByRun: "35",
    winByWicket: "0",
    playerOfMatch: "Yuvraj Singh",
  },
  {
    id: "qwertyuwrn13",
    year: 2015,
    date: "6/4/2015",
    city: "pune",
    tossWin: "Rising Pune Supergiant",
    tossDecision: "field",
    team1: "Mumbai Indians",
    team2: "Rising Pune Supergiant",
    winner: "Rising Pune Supergiant",
    winByRun: "0",
    winByWicket: "7",
    playerOfMatch: "SPD Smith",
  },
  {
    id: "qwertyun12fa98",
    year: 2015,
    date: "7/4/2015",
    city: "Rajkot",
    tossWin: "Kolkata Knight Riders",
    tossDecision: "Bat",
    team1: "Gujarat Lions",
    team2: "Kolkata Knight Riders",
    winner: "Kolkata Knight Riders",
    winByRun: "0",
    winByWicket: "10",
    playerOfMatch: "CA Lynn",
  },
  {
    id: "qwertyun89812",
    year: 2017,
    date: "5/4/2017",
    city: "Hyderabad",
    tossWin: "Royal Challengers Bangalore",
    tossDecision: "field",
    team1: "Sunrisers Hyderabad",
    team2: "Royal Challengers Bangalore",
    winner: "Sunrisers Hyderabad",
    winByRun: "35",
    winByWicket: "0",
    playerOfMatch: "Yuvraj Singh",
  },
  {
    id: "qwertyunqd13",
    year: 2017,
    date: "6/4/2017",
    city: "pune",
    tossWin: "Rising Pune Supergiant",
    tossDecision: "field",
    team1: "Mumbai Indians",
    team2: "Rising Pune Supergiant",
    winner: "Rising Pune Supergiant",
    winByRun: "0",
    winByWicket: "7",
    playerOfMatch: "SPD Smith",
  },
  {
    id: "qweczcrtyun12",
    year: 2017,
    date: "7/4/2017",
    city: "Rajkot",
    tossWin: "Kolkata Knight Riders",
    tossDecision: "Field",
    team1: "Gujarat Lions",
    team2: "Kolkata Knight Riders",
    winner: "Kolkata Knight Riders",
    winByRun: "0",
    winByWicket: "10",
    playerOfMatch: "CA Lynn",
  },
  {
    id: "qwerzctdfdyun12",
    year: 2013,
    date: "5/4/2013",
    city: "Hyderabad",
    tossWin: "Royal Challengers Bangalore",
    tossDecision: "field",
    team1: "Sunrisers Hyderabad",
    team2: "Royal Challengers Bangalore",
    winner: "Sunrisers Hyderabad",
    winByRun: "35",
    winByWicket: "0",
    playerOfMatch: "Yuvraj Singh",
  },
  {
    id: "qwertyuwrn13",
    year: 2015,
    date: "6/4/2015",
    city: "pune",
    tossWin: "Rising Pune Supergiant",
    tossDecision: "field",
    team1: "Mumbai Indians",
    team2: "Rising Pune Supergiant",
    winner: "Rising Pune Supergiant",
    winByRun: "0",
    winByWicket: "7",
    playerOfMatch: "SPD Smith",
  },
  {
    id: "qwertyucsn12fa",
    year: 2013,
    date: "7/4/2013",
    city: "Raipur",
    tossWin: "Kolkata Knight Riders",
    tossDecision: "Bat",
    team1: "Gujarat Lions",
    team2: "Kolkata Knight Riders",
    winner: "Kolkata Knight Riders",
    winByRun: "0",
    winByWicket: "10",
    playerOfMatch: "CA Lynn",
  },
];
